### ISSUE TITLE
use package.json to manage npm installs

### ISSUE THREAD

**Issue by scottdangelo** [IBM/summit-health-analytics#3]
This is pretty minor, since we only use npm for one package (csvtojson) for the generate.sh script, but it does allow the user to install in the local dir tree instead of globally.
I'll submit a patch.

**Comment by MaxShapiro32** [comment]
@scottdangelo Should https://github.com/IBM/summit-health-analytics/blob/master/generate/README.md be modified too to reflect this?

**Comment by scottdangelo** [comment]
oops. Your right, yes.
